name: main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Packages
        run: bash .github/workflows/packages.sh
